// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfxpqilajakhyetuyfpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmeHBxaWxhamFraHlldHV5ZnBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjA2NjEsImV4cCI6MjA2ODkzNjY2MX0.MXAN9s8GQ1IpkxDTH0yb1K4S4Jo8sdaNbOtxMJ-2drE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});